grubfood/grubfood/urls.py
from django.contrib import admin
from django.urls import include, path
# from django.http import HttpResponse

# def index(request):
#    return HttpResponse('<p>Hello! Welcome to <b>GrubFood</b>!</p>')

# def fgrub(request):
#    return HttpResponse('<p>Our featured grub for today is <b>Salmon Sashimi</b>!</p>')

urlpatterns = [
#    path('',index),
#    path('featuredgrub/', fgrub),
    path('webkiosk/', include('webkiosk.urls')),
    path('admin/', admin.site.urls),
]

grubfood/webkiosk/urls.py
from django.urls import path, include
from . import views

app_name = 'webkiosk'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('',include('django.contrib.auth.urls'),name='login'),
    # food
    path('food/', views.listfood, name='food-list'),
    path('food/new/', views.createfood, name='food-create'),
    path('food/<int:pk>/', views.detailfood, name='food-detail'),
    path('food/<int:pk>/edit/', views.updatefood, name='food-update'),
    path('food/<int:pk>/delete/', views.deletefood, name='food-delete'),
    # customers
    path('customers/', views.listcustomers, name='customer-list'),
    path('customers/new/', views.createcustomer, name='customer-create'),
    path('customers/<int:pk>/', views.detailcustomer, name='customer-detail'),
    path('customers/<int:pk>/edit/', views.updatecustomer, name='customer-update'),
    path('customers/<int:pk>/delete/', views.deletecustomer, name='customer-delete'),
    # Orders
    path('orders/', views.listorders, name='order-list'),
    path('orders/new/', views.createorder, name='order-create'),
    path('orders/<int:pk>/', views.detailorder, name='order-detail'),
    path('orders/<int:pk>/edit/', views.updateorder, name='order-update'),
    path('orders/<int:pk>/delete/', views.deleteorder, name='order-delete'),
]

grubfood/webkiosk/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    firstname = models.CharField(max_length=20)
    lastname = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    cellno = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.id}: {self.firstname} {self.lastname}, {self.address}, {self.city}, {self.email}, {self.cellno}'

class Food(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'{self.id}: {self.name} - {self.price}, {self.description}'

class Orders(models.Model):
    PAYMENT_MODE_CHOICES = [
        ('CH', 'Cash'),
        ('CD', 'Card')
    ]
    orderdatetime = models.DateTimeField(auto_now_add=True)
    paymentmode = models.CharField(max_length=2, choices=PAYMENT_MODE_CHOICES)
    quantity = models.IntegerField(default='0')

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self:id}: {self.customer.firstname} {self.customer.lastname}, {self.food.name}, {self.quantity}, {self.paymentmode}, {self.orderdatetime}'

# class OrderItem(models.Model):
#     quantity = models.IntegerField()
#
#     order = models.ForeignKey(Orders, on_delete=models.PROTECT)
#     food = models.ForeignKey(Food, on_delete=models.PROTECT, null=True, blank=True)
#
#     def __str__(self):
#         return f'{self.food.name} - {self.quantity}'

grubfood/webkiosk/forms.py
from django import forms
from django.forms import ModelForm, HiddenInput
from .models import Customer, Food, Orders

class FoodForm(ModelForm):
    class Meta:
        model = Food
        fields = ['name','description','price']

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['firstname','lastname','address','city','email','cellno']

class OrderForm(ModelForm):
    class Meta:
        model = Orders
        fields = ['paymentmode','customer','food']

# class OrderItemForm(ModelForm):
#     order = forms.IntegerField(widget=HiddenInput())
#     class Meta:
#         model = OrderItem
#         fields = ['food','quantity']

grubfood/webkiosk/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages

from .models import Customer, Food, Orders
from .forms import FoodForm, CustomerForm, OrderForm

# Create your views here.

def index(request):
    # return HttpResponse('<p>Welcome to the GrubFood Web Kiosk</p>')
    return render(request, 'webkiosk/welcome.html')

# food

def listfood(request):
    context = {
        'foodlist': Food.objects.all()
    }
    return render(request, 'webkiosk/food.html', context)

def createfood(request):
    if request.method == 'GET':
        form = FoodForm()
    elif request.method == 'POST':
        form = FoodForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:food-list')

    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

def detailfood(request, pk):
    food = Food.objects.get(id=pk)
    context = {'food':food}
    return render(request, 'webkiosk/food_detail.html', context)

def updatefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        form = FoodForm(instance=food)
    elif request.method == 'POST':
        form = FoodForm(request.POST, instance=food)
        if form.is_valid():
            form.save()
            messages.success(request, 'Food record successfully updated!')
    context = {'form':form}
    return render(request, 'webkiosk/food_form.html', context)

def deletefood(request, pk):
    food = Food.objects.get(id=pk)
    if request.method == 'GET':
        context = {'food':food}
        return render(request, 'webkiosk/food_delete.html', context)
    elif request.method == 'POST':
        food.delete()
        return redirect('webkiosk:food-list')

# customers

def listcustomers(request):
    context = {
        'customerlist': Customer.objects.all()
    }
    return render(request, 'webkiosk/customers.html', context)

def createcustomer(request):
    if request.method == 'GET':
        form = CustomerForm()
    elif request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:customer-list')

    context = {'form':form}
    return render(request, 'webkiosk/customer_form.html', context)

def detailcustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    context = {
    'customer':customer,
    'orderlist':Orders.objects.filter(customer=customer)
    }
    return render(request, 'webkiosk/customer_detail.html', context)

def updatecustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    if request.method == 'GET':
        form = CustomerForm(instance=customer)
    elif request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Customer record successfully updated!')
    context = {'form':form}
    return render(request, 'webkiosk/customer_form.html', context)

def deletecustomer(request, pk):
    customer = Customer.objects.get(id=pk)
    if request.method == 'GET':
        context = {'customer':customer}
        return render(request, 'webkiosk/customer_delete.html', context)
    elif request.method == 'POST':
        customer.delete()
        return redirect('webkiosk:customer-list')

# Orders

def listorders(request):
    context = {
        'orderlist': Orders.objects.all()
    }
    return render(request, 'webkiosk/orders.html', context)

def createorder(request):
    if request.method == 'GET':
        form = OrderForm()
        # orderitemform = OrderItemForm()
    elif request.method == 'POST':
        form = OrderForm(request.POST)
        # orderitemform = OrderItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('webkiosk:order-list')

    context = {'form':form}
    return render(request, 'webkiosk/order_form.html', context)

def detailorder(request, pk):
    order = Orders.objects.get(id=pk)
    context = {
    'order':order,
    'orderitemlist': OrderItem.objects.filter(order=order)
    }
    return render(request, 'webkiosk/order_detail.html', context)

def updateorder(request, pk):
    order = Orders.objects.get(id=pk)
    # orderitem = OrderItem.objects.filter(order=pk)
    if request.method == 'GET':
        form = OrderForm(instance=order)
        # orderitemform = OrderItemForm(initial={'order':pk})
    elif request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        # orderitemform = OrderItemForm(request.POST, instance=orderitem)
        if form.is_valid():
            form.save()
            # orderitemform.save()
            messages.success(request, 'Order record successfully updated!')
    context = {'form':form}
    return render(request, 'webkiosk/order_form.html', context)

def deleteorder(request, pk):
    order = Orders.objects.get(id=pk)
    if request.method == 'GET':
        context = {'order':order}
        return render(request, 'webkiosk/order_delete.html', context)
    elif request.method == 'POST':
        order.delete()
        return redirect('webkiosk:order-list')

grubfood/webkiosk/templates/webkiosk/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>{% block pagetitle %}{% endblock %}</title>
  </head>

  <body>

    {% block mainnav %}
    <nav>
      <ul>
        <li><a href="{% url 'webkiosk:food-list' %}">Food Menu</a></li>
        <li><a href="{% url 'webkiosk:food-create' %}">Add Food</a></li>
    </nav>
    {% endblock %}

    <header>
      <h1>GrubFood</h1>
      <p>Grub your food now!</p>
    </header>

    <main>
      {% block maincontent %}

      {% endblock %}
    </main>

  </body>

</html>

grubfood/webkiosk/templates/webkiosk/customer_delete.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Delete {{ customer.firstname }} {{ customer.lastname }}{% endblock %}

{% block mainnav %}{% endblock %}

{% block maincontent %}
<h2>delete customer</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete <b>{{ customer.firstname }}{{ customer.lastname }}</b>?</p>
  <a href="{% url 'webkiosk:customer-list' %}">Cancel</a>
  <input type="submit" value="Yes">
</form>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/customer_detail.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - {{ customer.name }}{% endblock %}

{% block maincontent %}
<h2>{{ customer.firstname }} {{ customer.lastname }}</h2>

<ul>
  <li>{{ customer.address }}</li>
  <li>{{ customer.city }}</li>
  <li>{{ customer.email }}</li>
  <li>{{ customer.cellno }}</li>
</ul>

<h3>Order Transactions</h3>

<table>
  <tr>
    <th>ORDER #</th>
    <th>ORDER DATE</th>
  </tr>
  {% for order in orderlist %}
    <tr>
      <td>{{ order.id }}</td>
      <td>{{ order.orderdatetime }}</td>
    </tr>
  {% endfor %}
</table>

<ul>
  <li><a href="{% url 'webkiosk:customer-update' customer.id %}">Edit Customer</a></li>
  <li><a href="{% url 'webkiosk:customer-delete' customer.id %}">Delete Customer</a></li>
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/customer_form.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Add or Edit Customer{% endblock %}

{% block maincontent %}
<h2>add or edit customer</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <input type="submit" value="Add Item">
</form>

<ul>
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/customers.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Customer List{% endblock %}

{% block maincontent %}
<h2>customers</h2>
<table>
  <tr>
    <th>ID</th>
    <th>NAME</th>
    <th>ADDRESS</th>
    <th>CONTACT NO.</th>
  </tr>
  {% for customer in customerlist %}
    <tr>
      <td>{{ customer.id }}</td>
      <td>{{ customer.firstname }} {{ customer.lastname }}</td>
      <td>{{ customer.city }}</td>
      <td>{{ customer.cellno }}</td>
      <td><a href="{% url 'webkiosk:customer-detail' customer.id %}">View Details</a></td>
      <td><a href="{% url 'webkiosk:customer-update' customer.id %}">Edit Item</a></td>
      <td><a href="{% url 'webkiosk:customer-delete' customer.id %}">Delete Item</a></td>
    </tr>
  {% endfor %}
</table>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/food.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Food List{% endblock %}

{% block maincontent %}
<h2>food items</h2>
<table>
  <tr>
    <th>ID</th>
    <th>NAME</th>
    <th>PRICE</th>
  </tr>
  {% for food in foodlist %}
    <tr>
      <td>{{ food.id }}</td>
      <td>{{ food.name }}</td>
      <td>{{ food.price }}</td>
      <td><a href="{% url 'webkiosk:food-detail' food.id %}">View Details</a></td>
      <td><a href="{% url 'webkiosk:food-update' food.id %}">Edit Item</a></td>
      <td><a href="{% url 'webkiosk:food-delete' food.id %}">Delete Item</a></td>
    </tr>
  {% endfor %}
</table>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/food_delete.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Delete {{ food.name }}{% endblock %}

{% block mainnav %}{% endblock %}

{% block maincontent %}
<h2>delete food</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete <b>{{ food.name }}</b>?</p>
  <a href="{% url 'webkiosk:food-list' %}">Cancel</a>
  <input type="submit" value="Yes">
</form>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/food_detail.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - {{ food.name }}{% endblock %}

{% block maincontent %}
<h2>{{ food.name }}</h2>

<ul>
  <li>Price: Php {{ food.price }}</li>
  <li>Description: {{ food.description }}</li>
</ul>

<ul>
  <li><a href="{% url 'webkiosk:food-update' food.id %}">Edit Item</a></li>
  <li><a href="{% url 'webkiosk:food-delete' food.id %}">Delete Item</a></li>
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/food_form.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Add or Edit Food{% endblock %}

{% block maincontent %}
<h2>add or edit food item</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <input type="submit" value="Add Item">
</form>

<ul>
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/order_delete.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Delete Order {{ order.id }}{% endblock %}

{% block mainnav %}{% endblock %}

{% block maincontent %}
<h2>delete order</h2>
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete <b>Order {{ order.id }}</b>?</p>
  <a href="{% url 'webkiosk:order-list' %}">Cancel</a>
  <input type="submit" value="Yes">
</form>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/order_detail.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Order {{ order.id }}{% endblock %}

{% block maincontent %}
<h2>Order #{{ order.id }}</h2>

<ul>
  <li>Order Date: {{ order.orderdatetime }}</li>
  <li>Payment Method: {{ order.paymentmode }}</li>
  <li>Customer: {{ order.customer.firstname }} {{ order.customer.lastname }}</li>
</ul>

<h3>Order Transactions</h3>

<table>
  <tr>
    <th>ITEM</th>
    <th>QTY</th>
    <th>PRICE</th>
  </tr>
  {% for orderitem in orderitemlist %}
    <tr>
      <td>{{ orderitem.food.name }}</td>
      <td>{{ orderitem.quantity }}</td>
      <td>{{ orderitem.food.price }}</td>
    </tr>
  {% endfor %}
</table>

<ul>
  <li><a href="{% url 'webkiosk:order-update' order.id %}">Edit Item</a></li>
  <li><a href="{% url 'webkiosk:order-delete' order.id %}">Delete Item</a></li>
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/order_form.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Add or Edit Order{% endblock %}

{% block maincontent %}
<h2>add or edit order item</h2>

<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <!-- {% for orderitem in orderitem %}
    {{ orderitemform.as_ul }}
  {% endfor %} -->
  <input type="submit" value="Add Item">
</form>

<ul>
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
</ul>

{% endblock %}

grubfood/webkiosk/templates/webkiosk/orders.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood - Order List{% endblock %}

{% block maincontent %}
<h2>food items</h2>
<table>
  <tr>
    <th>ORDER NO.</th>
    <th>CUSTOMER NAME</th>
    <th>CUSTOMER ID</th>
    <th>ORDER DATE</th>
  </tr>
  {% for order in orderlist %}
    <tr>
      <td>{{ order.id }}</td>
      <td>{{ order.customer.firstname }} {{ order.customer.lastname }}</td>
      <td>{{ order.customer.id }}</td>
      <td>{{ order.orderdatetime }}</td>
      <td><a href="{% url 'webkiosk:order-detail' order.id %}">View Details</a></td>
      <td><a href="{% url 'webkiosk:order-update' order.id %}">Edit Item</a></td>
      <td><a href="{% url 'webkiosk:order-delete' order.id %}">Delete Item</a></td>
    </tr>
  {% endfor %}
</table>
{% endblock %}

grubfood/webkiosk/templates/webkiosk/welcome.html
{% extends 'webkiosk/base.html' %}

{% block pagetitle %}GrubFood Web Kiosk{% endblock %}

{% block maincontent %}
<h2>Welcome</h2>
<p>Welcome to the GrubFood Web Kiosk! Have a nice day!</p>
{% endblock %}